In [72]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re

%matplotlib inline
sns.set;

### Initial Scraping Data of the KickStarter

In [110]:
colnames=['Project_Name', ' Inventor', 'Number_of_Backer', 
          'Total_Pledged', 'Goal', 'Location', 'Category', 
          'Number_of_Pledge_Options', 'Pledge_Detail', 'Status','useless'] 
Ks = pd.read_csv('KickStarter_data_utf8.csv', header=None, names=colnames)
Ks.reset_index(inplace = True)

In [111]:
Ks = Ks[colnames].drop(['useless'], axis = 1)

In [112]:
Ks.head(2)

,Project_Name,Inventor,Number_of_Backer,Total_Pledged,Goal,Location,Category,Number_of_Pledge_Options,Pledge_Detail,Status
0,This is not a Kickstarter shirt,Yancey,532.0,8554.0,500,New York-NY,Fashion,2,"('413 backers', 'US$ 15'), ('113 backers', 'US...",success
1,Family Secrets. A new doc style cooking show,Janet,117.0,5465.0,5000,New York-NY,Food,7,"('10 backers', '$10'), ('42 backers', '$20'), ...",success

### Rescraped Faillinks from the Initial Scraped

In [113]:
Ks2 = pd.read_csv('KickStarter_Faillinks_Rescrape.csv', header = None, names = colnames)

In [114]:
Ks2 = Ks2[colnames].drop(['useless'], axis = 1)

In [115]:
Ks2.head(2)

,Project_Name,Inventor,Number_of_Backer,Total_Pledged,Goal,Location,Category,Number_of_Pledge_Options,Pledge_Detail,Status
0,New & original design ~ London bus full size s...,Adian,2.0,6,69900.0,Shropshire-UK,Product Design,5,"('0 backers', '£1'), ('0 backers', '£20'), ('0...",live
1,The Oak Tree,Richard,2.0,750,16000.0,Marbella-Spain,Restaurants,4,"('0 backers', '€500'), ('1 backer', '€500'), (...",live

### Concat two datasets

In [116]:
frame = [Ks, Ks2]
df = pd.concat(frame)

In [117]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 34655 entries, 0 to 3795
Data columns (total 10 columns):
Project_Name                34655 non-null object
 Inventor                   33061 non-null object
Number_of_Backer            34644 non-null float64
Total_Pledged               34655 non-null object
Goal                        34655 non-null object
Location                    34655 non-null object
Category                    34655 non-null object
Number_of_Pledge_Options    34655 non-null object
Pledge_Detail               34638 non-null object
Status                      34655 non-null object
dtypes: float64(1), object(9)
memory usage: 2.9+ MB

In [118]:
df = df.drop_duplicates(keep=False)

In [119]:
df.info()
#looks like there was 117 duplicate projects, made a decision to drop them.

<class 'pandas.core.frame.DataFrame'>
Int64Index: 34538 entries, 0 to 3795
Data columns (total 10 columns):
Project_Name                34538 non-null object
 Inventor                   32948 non-null object
Number_of_Backer            34527 non-null float64
Total_Pledged               34538 non-null object
Goal                        34538 non-null object
Location                    34538 non-null object
Category                    34538 non-null object
Number_of_Pledge_Options    34538 non-null object
Pledge_Detail               34521 non-null object
Status                      34538 non-null object
dtypes: float64(1), object(9)
memory usage: 2.9+ MB

In [120]:
df = df.dropna()

In [121]:
df.info()
#also going to drop all nan rows

<class 'pandas.core.frame.DataFrame'>
Int64Index: 32920 entries, 0 to 3795
Data columns (total 10 columns):
Project_Name                32920 non-null object
 Inventor                   32920 non-null object
Number_of_Backer            32920 non-null float64
Total_Pledged               32920 non-null object
Goal                        32920 non-null object
Location                    32920 non-null object
Category                    32920 non-null object
Number_of_Pledge_Options    32920 non-null object
Pledge_Detail               32920 non-null object
Status                      32920 non-null object
dtypes: float64(1), object(9)
memory usage: 2.8+ MB

In [144]:
#df.loc[df.Total_Pledged == '¥1043200'] = df.loc[df.Total_Pledged == '¥1043200'].Total_Pledged.tolist()[0].lstrip('¥')

In [146]:
#all columns were scrapped and wrap into a string in order to avoid errors
#now we need to change some of the columns into numbers so that we can use for fitting.
df[['Number_of_Backer', 
     'Total_Pledged', 
     'Goal', 
     'Number_of_Pledge_Options']] = df[['Number_of_Backer', 
                                        'Total_Pledged', 
                                        'Goal', 
                                        'Number_of_Pledge_Options']].astype(float).astype(int)

,Project_Name,Inventor,Number_of_Backer,Total_Pledged,Goal,Location,Category,Number_of_Pledge_Options,Pledge_Detail,Status
0,This is not a Kickstarter shirt,Yancey,532,8554,500,New York-NY,Fashion,2,"('413 backers', 'US$ 15'), ('113 backers', 'US...",success
1,Family Secrets. A new doc style cooking show,Janet,117,5465,5000,New York-NY,Food,7,"('10 backers', '$10'), ('42 backers', '$20'), ...",success
3,"Shire Suds waste-free, handmade soap",Sarah,11,620,200,Old Town-ME,Crafts,4,"('4 backers', '$10'), ('2 backers', '$25'), ('...",success
4,The Let's Make a Bunch of Logos Project Part 3,Brandon,475,26243,25,Las Vegas-NV,Graphic Design,4,"('274 backers', '$25'), ('126 backers', '$50')...",success
5,9000 Wolves Short Film Project,Jamie,12,558,300,Reno-NV,Shorts,6,"('2 backers', '$1'), ('0 backers', '$10'), ('6...",success
6,Judas Kiss: A new gay film about second chance...,J.T.,85,10075,5000,Seattle-WA,Film & Video,11,"('6 backers', 'US$ 5'), ('12 backers', 'US$ 20...",success
8,The Urban Bounty: Growing Your Own Fresh Produ...,Green,149,8225,7500,Somerville-MA,Food,9,"('15 backers', '$15'), ('13 backers', '$25'), ...",success
9,Watch The Gap Fund Raiser for Dancers and Coll...,Ellen,80,2636,2500,Austin-TX,Dance,6,"('23 backers', 'US$ 1'), ('27 backers', 'US$ 2...",success
10,(ab)Normality,Sixth,53,2693,2600,Everett-WA,Performances,8,"('3 backers', 'US$ 10'), ('4 backers', 'US$ 15...",success
11,TEDDY-1,joko,283,11868,8000,San Francisco-CA,Comics,9,"('14 backers', '$5'), ('178 backers', '$30'), ...",success
12,NO‰Û¡åÊÌÒSPACE,NotAnAlternative,218,13177,10000,Brooklyn-NY,Art,12,"('59 backers', '$1'), ('50 backers', '$25'), (...",success
13,The Get Up,joe,54,2512,2400,San Diego-CA,Comics,23,"('5 backers', '$1'), ('8 backers', '$10'), ('1...",success
14,Oversharing is Caring (greetings cards more ho...,Jamie,32,597,500,Cuckfield-UK,Stationery,5,"('3 backers', 'Ì´å£1'), ('3 backers', 'Ì´å£3')...",success
15,Mako EDC Knife with CPM REX 121 Super Steel,Gary,51,13457,2700,Allentown-PA,Product Design,5,"('20 backers', '$199'), ('4 backers', '$249'),...",success
16,Evoke Dance Company Season 4 Kickstarter,Jeniffer,96,4645,4000,Los Angeles-CA,Dance,5,"('21 backers', '$1'), ('29 backers', '$25'), (...",success
17,Working Title: brain + vision + consciousness ...,Christian,53,18453,18000,Harlem-Manhattan-NY,Art,9,"('3 backers', '$10'), ('14 backers', '$25'), (...",success
18,COLONIE Restaurant coming soon to Brooklyn Hei...,COLONIE,91,15371,10000,Brooklyn-NY,Food,7,"('7 backers', '$10'), ('11 backers', '$25'), (...",success
19,PsychoPath Movie - A Documentary about a Garba...,Manny,74,5060,5000,Hood River-OR,Documentary,8,"('3 backers', '$1'), ('17 backers', '$10'), ('...",success
20,Giant Chocolate Meeples,Joe,25,1044,1000,Birmingham-AL,Food,14,"('3 backers', '$1'), ('0 backers', '$5'), ('7 ...",success
21,The Pay Phone Revival Project,Bridget,123,6260,5915,Austin-TX,Public Art,9,"('26 backers', '$5'), ('21 backers', '$10'), (...",success
22,RASCALS WITH ALTITUDE,General,27,3500,3000,New York-NY,Dance,9,"('1 backer', '$15'), ('1 backer', '$30'), ('3 ...",success
23,Shirts Created From a Kid's Imagination,Eric,47,4066,3925,Los Angeles-CA,Fashion,8,"('7 backers', '$15'), ('5 backers', '$20'), ('...",success
24,Soulbinder,Jimmy,43,1652,1500,Randolph-MA,Comic Books,7,"('3 backers', '$3'), ('16 backers', '$6'), ('1...",success
26,Magnifistick - Magnetic Key Holder,Oke,92,2057,1950,Fredericksburg-VA,Product Design,6,"('40 backers', '$13'), ('8 backers', '$13'), (...",success
27,A Murder of Crows,android0025,6,753,750,St. Paul-MN,Fashion,7,"('1 backer', '$10'), ('0 backers', '$25'), ('0...",success
28,Beads for the Chief,SALLY,101,3450,3000,New Orleans-LA,Mixed Media,10,"('2 backers', '$1'), ('31 backers', '$5'), ('3...",success
29,Violated Threads,Johnny,32,3001,3000,Brooklyn-NY,Fashion,9,"('0 backers', '$2'), ('1 backer', '$5'), ('9 b...",success
30,FACET pyramid iPad stand,iLoveHandles,174,17559,15000,Portland-OR,Product Design,8,"('1 backer', 'US$ 2'), ('3 backers', 'US$ 5'),...",success
31,OMG Jellyfish,Patti,309,41196,25000,San Francisco-CA,Product Design,13,"('33 backers', '$10'), ('4 backers', '$35'), (...",success
32,Edit,Melissa,95,2620,2000,Naperville-IL,Comics,14,"('3 backers', 'US$ 1'), ('1 backer', '$5'), ('...",success
...,...,...,...,...,...,...,...,...,...,...
3765,"Broken Bat Blog With Corey Mansfield, Support ...",Corey,1,10,5000,Clifton Park Center-NY,Web,3,"('1 backer', '$10'), ('0 backers', '$50'), ('0...",fail
3766,"make/100 - Mêlée, the Medieval Combat Card Game",Thomas,29,1292,1000,Warrenton-VA,Playing Cards,7,"('0 backers', '$1'), ('12 backers', '$16'), ('...",live
3767,Growing Pathways newspaper,Growingpathways,10,250,5000,Minneapolis-MN,Journalism,5,"('2 backers', '$10'), ('6 backers', '$20'), ('...",fail
3768,Benji Padgett - Solo EP,Benji,5,270,4500,Lakeland-FL,Music,9,"('0 backers', '$10'), ('1 backer', '$15'), ('2...",live
3769,How I Got Beat-Up By The FBI When I Was Four Y...,Dennis,1,6,160,Boulder-CO,Print,3,"('1 backer', '$6'), ('0 backers', '$12'), ('0 ...",fail
3770,Get Jnorth Media Off The Ground With New Equip...,Shiro,1,1,7000,Erie-PA,Web,5,"('0 backers', '$5'), ('0 backers', '$10'), ('0...",fail
3771,First African Muslim English Language Newspape...,SHEI,2,42,125000,Bronx-NY,Journalism,2,"('0 backers', '$30'), ('1 backer', '$30')",fail
3773,The Putumayo Project,Parker,6,423,3500,Puerto Putumayo-Colombia,Photo,7,"('2 backers', '$5'), ('1 backer', '$10'), ('0 ...",fail
3774,UNTRACKED TABLET MAGAZINE,Steamboat,10,355,35000,Steamboat Springs-CO,Journalism,10,"('3 backers', '$5'), ('2 backers', '$20'), ('2...",fail
3775,Butler Brothers Playing Cards,Parker,29,791,6095,Starkville-MS,Playing Cards,11,"('0 backers', '$10'), ('2 backers', '$16'), ('...",live
3776,Match Your Ghetto Food and Wine,Patricia,1,5,2000,Philadelphia-PA,Journalism,2,"('0 backers', '$1'), ('0 backers', '$5')",fail
3777,LUCKY a new recording,Carter,68,3677,15000,Oklahoma City-OK,Country & Folk,15,"('3 backers', 'US$ 10'), ('22 backers', '$15')...",live
3778,LGBT LIFESTYLE MAGAZINE,JOEY,2,230,15000,Chicago-IL,Journalism,14,"('0 backers', '$20'), ('1 backer', '$30'), ('0...",fail
3779,EsKape: Dragon Hunter,Tipping,4,128,8500,Orlando-FL,Video Games,5,"('3 backers', 'US$ 25'), ('1 backer', '$50'), ...",live
3780,Yay !!! Prostate Cancer...Now What? Surviving ...,Richard,3,46,5000,New Braunfels-TX,Web,1,"('0 backers', '$10')",fail
3781,BrainstormingUSA -- The Great American Magic A...,Joseph,6,169,35000,Phoenix-AZ,Web,9,"('1 backer', '$5'), ('0 backers', '$10'), ('1 ...",fail
3782,Music Tour,L.D.,1,500,45000,Atlanta-GA,Hip-Hop,2,"('1 backer', '$25')",live
3783,SKULLS AND BONES,RBJ,79,2783,500,Jonesboro-IN,Tabletop Games,7,"('5 backers', '$1'), ('39 backers', '$20'), ('...",live
3784,Elite Critique,Jeremy,3,46,5000,Kelowna-Canada,Video,1,"('0 backers', 'CA$ 1')",fail
3785,The Buskers Portraiture Project,The,14,326,6500,New Orleans-LA,Journalism,7,"('0 backers', '$1'), ('2 backers', '$10'), ('3...",fail
3786,Culture Clash,Christian,1,10,5000,Riverside-CA,Web,7,"('1 backer', '$10'), ('0 backers', '$20'), ('0...",fail
3787,GET MAUDE A GOPRO,Tersha,0,0,500,London-UK,Video,3,"('0 backers', '£10'), ('0 backers', '£100'), (...",fail
3788,Jay Bowcott's New Album,Jay,11,697,4000,Calgary-Canada,Country & Folk,7,"('1 backer', 'CA$ 20'), ('1 backer', 'CA$ 30')...",live
3789,Ultimate NPCs: Warfare for 5th Edition,Nord,495,20252,10000,Santa Cruz-CA,Tabletop Games,9,"('25 backers', '$1'), ('179 backers', '$15'), ...",live
3790,Ghost Hunting with Wayward Wanderers in Gettys...,Christina,0,0,100,Gettysburg-PA,Web,3,"('0 backers', '$5'), ('0 backers', '$20'), ('0...",fail
3791,DC Radio,DC,0,0,3500,Toronto-Canada,Audio,1,"('0 backers', 'CA$ 20')",fail
3792,The Memo,The,42,3845,40000,Berlin-Germany,Journalism,7,"('21 backers', '$25'), ('2 backers', '$50'), (...",fail
3793,VINILO FHHx - Sick Beat For Coleman,Mutown,3,90,3000,Murcia-Spain,Hip-Hop,5,"('0 backers', '€8'), ('3 backers', '€20'), ('0...",live
3794,Traffic Planner,Vostok,19,46780,222222,Kushiro-shi-Japan,Video Games,3,"('7 backers', '¥500'), ('12 backers', '¥1,500')",live
3795,Art Book & Limited Edition Pin - Make/100,Naomi,116,4703,700,Oakland-CA,Art Books,4,"('1 backer', '$1'), ('22 backers', '$20'), ('9...",live

In [147]:
df.to_csv('KickStarter_Luther.csv', index = False)